// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'physical-ai-humanoid-robotics/index',
    {
      type: 'autogenerated',
      dirName: 'physical-ai-humanoid-robotics',
    },
  ],
  module2Sidebar: [
    'module-2/index',
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo & Unity)',
      items: [
        'module-2/chapter-1-content',
        'module-2/chapter-2-content',
        'module-2/chapter-3-content',
      ],
    },
  ],
  module3Sidebar: [
    'module-3/index',
    {
      type: 'autogenerated',
      dirName: 'module-3',
    },
  ],
  module4Sidebar: [
    'module-4/index',
    {
      type: 'autogenerated',
      dirName: 'module-4',
    },
  ],
};

export default sidebars;